[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/prometheus/common"
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true
